name: uda_project_3
channels:
  - conda-forge
  - defaults
dependencies:
- python
- pip
- scikit-learn
- dvc[all]
- pandas
- numpy
- pytest
- jupyter
- jupyterlab
- fastapi
- uvicorn
- yapf
- pylint
- black

