stages:
  fix_spaces:
    cmd: sed 's/, /,/g' data/raw/census.csv > data/processed/census-fix-spaces.csv
    deps:
    - data/raw/census.csv
    outs:
    - data/processed/census-fix-spaces.csv
  remove_dups:
    cmd: awk '{counts[-zsh]++;if (counts[-zsh] == 1) {print -zsh}}' data/processed/census-fix-spaces.csv
      > data/processed/census-fix-spaces-nodups.csv
    deps:
    - data/processed/census-fix-spaces.csv
    outs:
    - data/processed/census-fix-spaces-nodups.csv
